<?php
define('AMBERGROUPS', array(
	'AMBER Alert Staff/Associates' => __('AMBER Alert Staff/Associates', 'amber'),
	'Internation Centre for Missing and Exploited Children' => __('Internation Centre for Missing and Exploited Children', 'amber'),
	'National Criminal Justice Training Center Staff/Associates' => __('National Criminal Justice Training Center Staff/Associates', 'amber'),
	'National Center for Missing and Exploited Children' => __('National Center for Missing and Exploited Children', 'amber'),
	'US Department of Justice Officials/Staff' => __('US Department of Justice Officials/Staff', 'amber'),
	)
);
define( 'USSTATES' , array(
	'Alabama' => __('Alabama', 'amber'),
	'Alaska' => __('Alaska', 'amber'),
	'American Samoa' => __('American Samoa', 'amber'),
	'Arizona' => __('Arizona', 'amber'),
	'Arkansas' => __('Arkansas', 'amber'),
	'California' => __('California', 'amber'),
	'Colorado' => __('Colorado', 'amber'),
	'Connecticut' => __('Connecticut', 'amber'),
	'Delaware' => __('Delaware', 'amber'),
	'District of Columbia' => __('District of Columbia', 'amber'),
	'Federated States of Micronesia' => __('Federated States of Micronesia', 'amber'),
	'Florida' => __('Florida', 'amber'),
	'Georgia' => __('Georgia', 'amber'),
	'Guam' => __('Guam', 'amber'),
	'Hawaii' => __('Hawaii', 'amber'),
	'Idaho' => __('Idaho', 'amber'),
	'Illinois' => __('Illinois', 'amber'),
	'Indiana' => __('Indiana', 'amber'),
	'Iowa' => __('Iowa', 'amber'),
	'Kansas' => __('Kansas', 'amber'),
	'Kentucky' => __('Kentucky', 'amber'),
	'Louisiana' => __('Louisiana', 'amber'),
	'Maine' => __('Maine', 'amber'),
	'Marshall Islands' => __('Marshall Islands', 'amber'),
	'Maryland' => __('Maryland', 'amber'),
	'Massachusetts' => __('Massachusetts', 'amber'),
	'Michigan' => __('Michigan', 'amber'),
	'Minnesota' => __('Minnesota', 'amber'),
	'Mississippi' => __('Mississippi', 'amber'),
	'Missouri' => __('Missouri', 'amber'),
	'Montana' => __('Montana', 'amber'),
	'Nebraska' => __('Nebraska', 'amber'),
	'Nevada' => __('Nevada', 'amber'),
	'New Hampshire' => __('New Hampshire', 'amber'),
	'New Jersey' => __('New Jersey', 'amber'),
	'New Mexico' => __('New Mexico', 'amber'),
	'New York' => __('New York', 'amber'),
	'North Carolina' => __('North Carolina', 'amber'),
	'North Dakota' => __('North Dakota', 'amber'),
	'Northern Mariana Islands' => __('Northern Mariana Islands', 'amber'),
	'Ohio' => __('Ohio', 'amber'),
	'Oklahoma' => __('Oklahoma', 'amber'),
	'Oregon' => __('Oregon', 'amber'),
	'Palau' => __('Palau', 'amber'),
	'Pennsylvania' => __('Pennsylvania', 'amber'),
	'Puerto Rico' => __('Puerto Rico', 'amber'),
	'Rhode Island' => __('Rhode Island', 'amber'),
	'South Carolina' => __('South Carolina', 'amber'),
	'South Dakota' => __('South Dakota', 'amber'),
	'Tennessee' => __('Tennessee', 'amber'),
	'Texas' => __('Texas', 'amber'),
	'Utah' => __('Utah', 'amber'),
	'Vermont' => __('Vermont', 'amber'),
	'Virgin Islands' => __('Virgin Islands', 'amber'),
	'Virginia' => __('Virginia', 'amber'),
	'Washington' => __('Washington', 'amber'),
	'West Virginia' => __('West Virginia', 'amber'),
	'Wisconsin' => __('Wisconsin', 'amber'),
	'Wyoming' => __('Wyoming', 'amber'),
	)
);

define('CANADIANSTATES', array(
	'Alberta' => __('Alberta', 'amber'),
	'British Columbia' => __('British Columbia', 'amber'),
	'Manitoba' => __('Manitoba', 'amber'),
	'New Brunswick' => __('New Brunswick', 'amber'),
	'Newfoundland and Labrador' => __('Newfoundland and Labrador', 'amber'),
	'Nova Scotia' => __('Nova Scotia', 'amber'),
	'Northwest Territories' => __('Northwest Territories', 'amber'),
	'Nunavut' => __('Nunavut', 'amber'),
	'Ontario' => __('Ontario', 'amber'),
	'Prince Edward Island' => __('Prince Edward Island', 'amber'),
	'Quebec' => __('Quebec', 'amber'),
	'Saskatchewan' => __('Saskatchewan', 'amber'),
	'Yukon' => __('Yukon', 'amber'),
	)
);

define('MEXICANSTATES', array(
	'Aguascalientes' => __('Aguascalientes', 'amber'),
	'Baja California' => __('Baja California', 'amber'),
	'Baja California Sur' => __('Baja California Sur', 'amber'),
	'Campeche' => __('Campeche', 'amber'),
	'Chiapas' => __('Chiapas', 'amber'),
	'Chihuahua' => __('Chihuahua', 'amber'),
	'Coahuila' => __('Coahuila', 'amber'),
	'Colima' => __('Colima', 'amber'),
	'Mexico City' => __('Mexico City', 'amber'),
	'Durango' => __('Durango', 'amber'),
	'Guanajuato' => __('Guanajuato', 'amber'),
	'Guerrero' => __('Guerrero', 'amber'),
	'Hidalgo' => __('Hidalgo', 'amber'),
	'Jalisco' => __('Jalisco', 'amber'),
	'México' => __('México', 'amber'),
	'Michoacán' => __('Michoacán', 'amber'),
	'Morelos' => __('Morelos', 'amber'),
	'Nayarit' => __('Nayarit', 'amber'),
	'Nuevo León' => __('Nuevo León', 'amber'),
	'Oaxaca' => __('Oaxaca', 'amber'),
	'Puebla' => __('Puebla', 'amber'),
	'Querétaro' => __('Querétaro', 'amber'),
	'Quintana Roo' => __('Quintana Roo', 'amber'),
	'San Luis Potosí' => __('San Luis Potosí', 'amber'),
	'Sinaloa' => __('Sinaloa', 'amber'),
	'Sonora' => __('Sonora', 'amber'),
	'Tabasco' => __('Tabasco', 'amber'),
	'Tamaulipas' => __('Tamaulipas', 'amber'),
	'Tlaxcala' => __('Tlaxcala', 'amber'),
	'Veracruz' => __('Veracruz', 'amber'),
	'Yucatán' => __('Yucatán', 'amber'),
	'Zacateca' => __('Zacateca', 'amber'),
	)
);
?>